scala:
  build: ./
  links:
    - kafka:kafka
  environment:
    KAFKA_HOST: kafka:9092
zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181"
kafka:
  image: wurstmeister/kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    KAFKA_CREATE_TOPICS: "lowercaseString:1:3,uppercaseString:1:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
