---
- hosts: all
  vars:
    mysql_db: mailserver
    mysql_user: dovecot
    mysql_pass: abc123
    ssl_cert: /etc/ssl/certs/lukasmartinelli.pem
    ssl_key: /etc/ssl/private/lukasmartinelli.pem
    mail_home: /var/mail/%d/%u
    mail_location: maildir:{{ mail_home }}:LAYOUT=fs
    dkim_domain: lukasmartinelli.ch
    dkim_key: /etc/opendkim/keys/lukasmartinelli.ch/mail.private
  pre_tasks:
    - name: Copy Server Certificate
      sudo: yes
      copy: src=public.pem dest={{ ssl_cert }}
    - name: Copy Server private key
      sudo: yes
      copy: src=private.pem dest={{ ssl_key }}
  roles:
    - mysql
    - postfix
    - dovecot
    - dkim
