[template]
src = "nginx.tmpl"
dest = "/etc/nginx/nginx.conf"
keys = [
    "/redirekter/domains",
]
owner = "root"
mode = "0644"
check_cmd = "/usr/sbin/nginx -t"
reload_cmd = "/usr/sbin/service nginx reload"
