- name: create deployment user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ db_deploy_user }}
              password={{ db_deploy_pass }}
              state=present


- name: create database for mail users
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ db_name }} owner={{ db_deploy_user }} state=present

- name: create Postfix user
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{ db_name }}
              name={{ db_postfix_user }}
              password={{ db_postfix_pass }}
              state=present

- name: create Dovecot user
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{ db_name }}
              name={{ db_dovecot_user }}
              password={{ db_dovecot_pass }}
              state=present

- name: copy table setup script
  copy: src=tables.sql dest=/tmp/tables.sql

  #Script should be executed as deploy user
- name: create tables with setup script
  sudo: yes
  sudo_user: postgres
  shell: psql -v ON_ERROR_STOP=1 -d {{ db_name }} -a -f /tmp/tables.sql
  register: psql_result
  failed_when: >
              psql_result.rc != 0 and ("already exists" not in psql_result.stderr)
  changed_when: "psql_result.rc == 0"

