- name: install server and Python support
  sudo: yes
  action: apt name={{ item }} state=present
  notify: start postgresql server
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- include: database.yml
